# Generated by Django 4.1.5 on 2024-02-12 04:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_name",
                    models.CharField(blank=True, default="", max_length=55, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=55, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("createDate", models.DateTimeField(default=django.utils.timezone.now)),
                ("updateDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModuleDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_name",
                    models.CharField(blank=True, default="", max_length=55, null=True),
                ),
                ("module_amount", models.FloatField(blank=True, null=True)),
                (
                    "module_type",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        max_length=55,
                        verbose_name="Module Choices",
                    ),
                ),
                ("module_details", models.TextField(blank=True, null=True)),
                ("module_validity", models.IntegerField(blank=True, null=True)),
                ("createDate", models.DateTimeField(default=django.utils.timezone.now)),
                ("updateDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_name",
                    models.CharField(blank=True, default="", max_length=55, null=True),
                ),
                ("createDate", models.DateTimeField(default=django.utils.timezone.now)),
                ("updateDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="user_role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_roles",
                    models.CharField(blank=True, default="", max_length=55, null=True),
                ),
                ("createDate", models.DateTimeField(default=django.utils.timezone.now)),
                ("updateDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="role_has_permissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminSite.permission",
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminSite.user_role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_details", models.TextField(blank=True, null=True)),
                ("discount", models.FloatField(blank=True, null=True)),
                ("sub_total", models.FloatField(blank=True, null=True)),
                ("grand_total", models.FloatField(blank=True, null=True)),
                ("createDate", models.DateTimeField(default=django.utils.timezone.now)),
                ("updateDate", models.DateTimeField(auto_now=True)),
                (
                    "module_details_id",
                    models.ManyToManyField(blank=True, to="adminSite.moduledetails"),
                ),
            ],
        ),
    ]
