# Generated by Django 4.1.5 on 2024-02-12 05:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("adminSite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwningType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "awning_name",
                    models.CharField(blank=True, default="", max_length=55, null=True),
                ),
                (
                    "awning_color",
                    models.CharField(blank=True, default="", max_length=55, null=True),
                ),
                ("awning_price", models.FloatField(blank=True, null=True)),
                ("createDate", models.DateTimeField(default=django.utils.timezone.now)),
                ("updateDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FabricType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fabric_name",
                    models.CharField(blank=True, default="", max_length=55, null=True),
                ),
                (
                    "fabric_color",
                    models.CharField(blank=True, default="", max_length=55, null=True),
                ),
                ("fabric_price", models.FloatField(blank=True, null=True)),
                ("createDate", models.DateTimeField(default=django.utils.timezone.now)),
                ("updateDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount", models.FloatField(blank=True, null=True)),
                ("sub_total", models.FloatField(blank=True, null=True)),
                ("grand_total", models.FloatField(blank=True, null=True)),
                ("createDate", models.DateTimeField(default=django.utils.timezone.now)),
                ("updateDate", models.DateTimeField(auto_now=True)),
                (
                    "awningtype_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminSite.awningtype",
                    ),
                ),
                (
                    "fabrictype_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminSite.fabrictype",
                    ),
                ),
            ],
        ),
    ]
