# Generated by Django 4.1.5 on 2024-02-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminSite", "0002_awningtype_fabrictype_sales"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="sales",
            new_name="Cost",
        ),
    ]
