# Generated by Django 4.1.5 on 2024-02-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminSite", "0003_rename_sales_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cost",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="cost",
            name="grand_total",
        ),
    ]
