# Generated by Django 4.1.5 on 2024-02-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminSite", "0004_remove_cost_discount_remove_cost_grand_total"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cost",
            old_name="sub_total",
            new_name="total",
        ),
    ]
